### ISSUE TITLE
List of face gestures goes off screen

### ISSUE THREAD

**Issue by gavinhenderson** [AceCentre/FaceCommander#14]
The list of scroll gestures goes out the bounds of the window. This means that depending on where the window is some face gestures are in accessible. You can move the window and access them but its a tad annoying and if the list gets longer the issue will get worse.

I would suggest maybe forcing the dropdown to somehow stay in the bounds of the window and then making is scroll, similar to how a normal select element would work.

![image](https://github.com/AceCentre/FaceCommander/assets/1359202/27e56c5e-bea7-43eb-9498-cec2334b976e)

**Comment by sjjhsjjh** [comment]
Hi, I'm wondering if it would be better to have a page with the map from gestures to actions, instead of having the gestures on a drop-down at all?

**Comment by gavinhenderson** [comment]
@sjjhsjjh thats a great idea, i think that is better UX for new users aswell, being able to see all the gestures at once.

**Comment by acidcoke** [comment]
> Hi, I'm wondering if it would be better to have a page with the map from gestures to actions, instead of having the gestures on a drop-down at all?

I like this a lot. This would allow us to trigger actions with multiple gestures

**Comment by sjjhsjjh** [comment]
Hi again, Maybe a silly question but would we ever want the same gesture with difference sizes to trigger different actions?

**Comment by willwade** [comment]
Everything is feasible with Assistive Technology! I would say it's definitely not a primary use case but it definitely could occur. Take for example blinking it's possible you may have a short blink and a long blink to do two different actions or say open for a period of time. equally a little smile or a large smile different actions. Difficult to use it for sure.

**Comment by gavinhenderson** [comment]
I think what those options are for is to control the keyboard interaction.

Dynamic - Holds the key for the entire time you are over the threshold
Rapid - Does a very quick click
Single - 'Normal' click
Hold - Long holds the keypress
Toggle - Is like a latch

As will says they are useful to have. That being said, the UI could be improved so its clearer what they do.

> Same gesture sizes to trigger different actions

Whilst I agree with Will everything is possible and it would be nice to allow it. However, I think I would rather improve the UI for the 'standard' usage first of one gesture to one action. Then down the line we can come up with a clean way to do the multiple gestures and actions. 

So for now, lets just assume one gesture to one action and we can improve it down the line

**Comment by sjjhsjjh** [comment]
Thanking you both.
I'll call the dynamic etc the Modifier.
Can a Modifier be applied to a mouse action? If it can then a user could do a drag and drop (DnD) interaction like this.

- Configure Open Mouth to do Action: Left Click Mouse with Modifier: Dynamic.
- Activate face control of the pointer.

1. Turn their head to position the pointer over the DnD object.
2. Open their mouth, which will select the object.
3. Turn their head again to drag the object to its target.
4. Close their mouth, which will release the object.

It seems like the ultimate mapping structure could be like Gesture+SizeRange => Action+Modifier.
The current simplification is that the top of the SizeRange is always the maximum.

**Comment by acidcoke** [comment]
Sorry for the confusion. Altough the description needs some work I did add it to the readme file.

> I think what those options are for is to control the keyboard interaction.

Yes, but also for mice

- Dynamic - When the threshold of the gesture is reached, the key or mouse button is clicked once but if certain amount of time has passed the key is being kept pressed until the gesture is under the threshold again

  This is necessary when you are using FaceCommander as a direct replacement for the mouse. If the button was held immediately after reaching the threshold, you would always drag everything.

- Rapid - This should be called rapid fire. Mostly useful in shooters or quick time events

The others are as described by @gavinhenderson 
  > Single - 'Normal' click
  > Hold - Long holds the keypress
  > Toggle - Is like a latch

**Comment by willwade** [comment]
NB fixed this for now just adding a scroll bar to this dropdown https://github.com/AceCentre/FaceCommander/commit/4b591b5f2cdce40ce653209b7fa1a9c2c2f8f1d8

I'll leave this open for now though as @sjjhsjjh  ideas for a seperate page is better.. 

just gonna have to find time to do it
