### ISSUE TITLE
Profiles are buggy

### ISSUE THREAD

**Issue by gavinhenderson** [AceCentre/FaceCommander#3]
The 'profiles' setup is a great feature but I have found it slightly buggy.

When you delete a profile it doesn't disappear immediately. The 'rename' button doesn't do anything. After pressing delete you end up with a weirdly named profile.

**Comment by sjjhsjjh** [comment]
Hi @gavinhenderson , I had a bit of a do on the Configuration Manager class near here.
https://github.com/AceCentre/FaceCommander/pull/24/files#diff-ef4a53b677364de1ed876cd132654cc7336200d9a2629fe49ecc2a0dd8a91862

I think it fixed the issues mentioned above but do please have a look and confirm, or not.

**Comment by gavinhenderson** [comment]
That seems to have fixed the issues, thanks @sjjhsjjh
