### ISSUE TITLE
Can I use this for just basic usage, web browser on my PC?

### ISSUE THREAD

**Issue by kingy000** [AceCentre/FaceCommander#30]
Can I use this for just basic usage, web browser on my PC?
Also will this work for RuneScape game?
Can't open it

I have a physical disability which causes my hand movement very slow for using the mouse.

**Comment by willwade** [comment]
sorry for not answering this earlier.. you'd be better looking at GrimAssist https://github.com/acidcoke/Grimassist?tab=readme-ov-file#grimassist

We are migrating away from headcontrol for a while till we get other things settled..
