### ISSUE TITLE
Remove mouse controls

### ISSUE THREAD

**Issue by gavinhenderson** [AceCentre/FaceCommander#34]
The mouse controls are all a bit broken.

We don't want to go down this rabbit hole at the minute. We will come back to it at some point but once we have more capacity.

**Comment by acidcoke** [comment]
Do you mean only the cursor or also mouse buttons?

**Comment by gavinhenderson** [comment]
Im referencing both the cursor and also the mouse buttons.

I've made a start on the branch https://github.com/AceCentre/FaceCommander/tree/remove-mouse-control

Whilst the mouse controls are really good we have had tons of difficult to solve niche errors on every different device. Mainly touch devices hiding the mouse, some let us force show it, others don't its really tricky. Some devices it works fine on.

Our thinking behind removing those features is we are planning on launching and supporting this app with our clients and it would be too difficult to adequately support them with these tricky issues. We also know that head mouse control is something that we can use other solutions for, which we currently do with our clients so they are not missing out.

On the other hand the face gestures for keyboard control is something thats not done great in any alternatives so thats why we want to initially focus on this. 

Im hoping we can eventually roll out mouse control but right now its really blocking us rolling out.
