### ISSUE TITLE
Obscuring bottom half of face

### ISSUE THREAD

**Issue by willwade** [AceCentre/FaceCommander#47]
If have a client with an obscured face it seems to still detect blink but not eyebrow. Why?

Try with a facemask covering mouth and lower nose. Sure - we wouldnt expect to do mouth or cheeks but eyes and brows etc I was hoping for. Can we improve this?

**Comment by willwade** [comment]
Try 

`mp_face_mesh.FaceMesh(min_detection_confidence=0.3)
`

failing that here are some ideas.. 


1. Adjusting Detection Threshold

You can adjust the min_detection_confidence parameter when initializing the FaceMesh object. Lowering it helps to detect features even with partial face occlusion.

```
import cv2
import mediapipe as mp

# Initialize MediaPipe FaceMesh
mp_face_mesh = mp.solutions.face_mesh
face_mesh = mp_face_mesh.FaceMesh(
    static_image_mode=False,
    max_num_faces=1,
    min_detection_confidence=0.3,  # Lowering the confidence threshold
    min_tracking_confidence=0.5
)

# Initialize MediaPipe drawing utils
mp_drawing = mp.solutions.drawing_utils

# Open video capture
cap = cv2.VideoCapture(0)

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Convert the BGR image to RGB
    rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    
    # Process the frame with the FaceMesh
    results = face_mesh.process(rgb_frame)

    # Draw face mesh landmarks
    if results.multi_face_landmarks:
        for face_landmarks in results.multi_face_landmarks:
            mp_drawing.draw_landmarks(
                image=frame,
                landmark_list=face_landmarks,
                connections=mp_face_mesh.FACE_CONNECTIONS,
                landmark_drawing_spec=None,
                connection_drawing_spec=mp_drawing.DrawingSpec(
                    color=(0, 255, 0), thickness=1, circle_radius=1
                )
            )
    
    # Display the frame
    cv2.imshow('Face Mesh', frame)

    # Break loop on 'q' key
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release resources
cap.release()
cv2.destroyAllWindows()
```

2. Cropping the Region of Interest (ROI) for Upper Face (Eyes and Eyebrows)

You can define a bounding box around the upper half of the face to focus only on detecting eyes and eyebrows. The landmarks for the eyes and eyebrows are roughly between landmarks 0 and 467 in the mediapipe face mesh.

```
import cv2
import mediapipe as mp

# Initialize MediaPipe FaceMesh
mp_face_mesh = mp.solutions.face_mesh
face_mesh = mp_face_mesh.FaceMesh(
    static_image_mode=False,
    max_num_faces=1,
    min_detection_confidence=0.3,
    min_tracking_confidence=0.5
)

# Initialize MediaPipe drawing utils
mp_drawing = mp.solutions.drawing_utils

# Open video capture
cap = cv2.VideoCapture(0)

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Convert the BGR image to RGB
    rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    
    # Process the frame with the FaceMesh
    results = face_mesh.process(rgb_frame)

    # Draw only the eyes and eyebrow landmarks
    if results.multi_face_landmarks:
        for face_landmarks in results.multi_face_landmarks:
            # Get the list of landmarks for the eyes and eyebrows
            for idx in range(0, 468):  # Landmarks for eyes and upper part of the face
                x = int(face_landmarks.landmark[idx].x * frame.shape[1])
                y = int(face_landmarks.landmark[idx].y * frame.shape[0])

                # Draw a small circle for each landmark
                cv2.circle(frame, (x, y), 2, (0, 255, 0), -1)
    
    # Display the cropped frame
    cv2.imshow('Face Mesh - Eye and Eyebrow Region', frame)

    # Break loop on 'q' key
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release resources
cap.release()
cv2.destroyAllWindows()
```

**Comment by RF9862** [comment]
Hi, Checked your issues.
Raise eyebrow is working well  in an obscured and whole face, but not working in Lower eyebrow.
Lower eyebrow is not working well in even whole face, too. 
It is problem related with detection size of lower eyebrow.

Because tracking_location is detected, eye brow gesture is not affected greatly according to obscured or whole face.
Even on the surface, raise eyebrow effect is more clear than greater than lower eyebrow effect.
But, lower eyebrow effect is existed. So , for simple solution, we can  scale for detection size of lower eyebrow. 

In line 136 of facemesh.py, 
def get_blendshapes(self) -> npt.ArrayLike:  
    self. smooth_blendshapes[x1] = self.smooth_blendshapes * k
    self. smooth_blendshapes[x2] = self.smooth_blendshapes * k

    return self.smooth_blendshapes
Here, x1, x2 ,... are index of gestures related with lower eyebrow, k: scaling constant.

**Comment by willwade** [comment]
I'm going to close this until we get a chance to fully test this out.
