### ISSUE TITLE
add ignore repeats

### ISSUE THREAD

**Issue by willwade** [AceCentre/FaceCommander#58]
https://github.com/google/project-gameface/issues/39#issuecomment-1783927041

We used to have throttle time. I think we need a general Setting (or should be it on each item?) to avoid double presses rapidly

It in effect ignores repeated presses if within a set time threshold. should be 0-3seconds

**Comment by willwade** [comment]
@alex5105 - have a think before implementing this. I cant decide whether this should be on each gesture or global. I'm not sure whats best

**Comment by alex5105** [comment]
okay, got it.
